-
  name: Install apache on web node
  hosts: web
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: present
    - name: start apache
      service:
        name: httpd
        state: started
