<<<<<<< HEAD
-
  name: Install oracle weblogic12
  hosts: app
  vars:
     java_dir: /home/ec2-user/jdk1.8.0_231
     mw_dir: /tmp
     mw_installer: fmw_12.2.1.4.0_wls_quick.jar
     oracle_home: /home/ec2-user/fmw
  tasks:
    - name: copy fmw jar file to app nodes
      copy:
        src: /tmp/fmw_12.2.1.4.0_wls_quick_Disk1_1of1.zip
        dest: /tmp
    - name: unzip fwm file in app nodes
      unarchive:
        src: /tmp/fmw_12.2.1.4.0_wls_quick_Disk1_1of1.zip
        dest: /tmp
        remote_src: yes
    - name: copy install script and properties
      copy:
        src: ~/learn-ansible/weblogic_install/{{ item }}
        dest: /tmp
        mode: "a+r"
      loop:
        [oraInst.loc,wls_install.rsp]
    - name: weblogic isntall
      command:
        "{{ java_dir }}/bin/java -jar  {{ mw_dir }}/{{ mw_installer }} -ignoreSysPrereqs -force -novalidation
          ORACLE_HOME={{ oracle_home }} -responseFile {{ mw_dir }}/wls_install.rsp -invPtrLoc {{ mw_dir }}/oraInst.loc"
      register: command_result
    - debug: msg={{ command_result.stdout.split('\n')[:-1]}}
    - name: Wait for installation complete
      pause:
        minitues: 3
=======
-
  name: Install oracle weblogic12
  hosts: app
  vars:
     java_dir: /home/ec2-user/jdk1.8.0_231
     mw_dir: /tmp
     mw_installer: fmw_12.2.1.4.0_wls_quick.jar
     oracle_home: /home/ec2-user/fmw
  tasks:
    - name: copy fmw jar file to app nodes
      copy:
        src: /tmp/fmw_12.2.1.4.0_wls_quick_Disk1_1of1.zip
        dest: /tmp
    - name: unzip fwm file in app nodes
      unarchive:
        src: /tmp/fmw_12.2.1.4.0_wls_quick_Disk1_1of1.zip
        dest: /tmp
        remote_src: yes
    - name: copy install script and properties
      copy:
        src: ~/learn-ansible/weblogic_install/{{ item }}
        dest: /tmp
        mode: "a+r"
      loop:
        [oraInst.loc,wls_install.rsp]
    - name: weblogic isntall
      command:
        "{{ java_dir }}/bin/java -jar  {{ mw_dir }}/{{ mw_installer }} -ignoreSysPrereqs -force -novalidation
          ORACLE_HOME={{ oracle_home }} -responseFile {{ mw_dir }}/wls_install.rsp -invPtrLoc {{ mw_dir }}/oraInst.loc"
      register: command_result
>>>>>>> a360bd5ec79090d18346a3dba059abbe79a221e6
