---
- name: Install Java 8 using YUM.
  yum:
    name: "{{java.VERSION}}"
    state: latest
  become: true

- name: Correct the alternatives to change default Java version.
  alternatives:
    name: java
    link: /bin/java
    path: "{{java.ALTERNATIVES}}"

- name: set JAVA_HOME for user
  lineinfile:
    dest: ~/.bash_profile
    regexp: '^# User specific environment'
    line: "{{ item }}"
  with_items:
    - 'JAVA_HOME="{{java.JAVA_HOME}}"'
    - 'export JAVA_HOME'
    - 'PATH=$PATH:$JAVA_HOME/bin'

- name: reload bash profile file
  shell: source ~/.bash_profile

- name: echo JAVA_HOME variable path
  command: echo "$JAVA_HOME"
  environment:
    JAVA_HOME: "{{java.JAVA_HOME}}"
  register: shell_out
  
- name: print java home path
  debug:
    msg: "{{shell_out.stdout}}"

- name: Download Jenkins repo yum URL for
  get_url:
    url: "{{jenkins.repo_URL}}"
    dest: /etc/yum.repos.d/jenkins.repo
  become: true

- name: Import GPG Key
  rpm_key:
    state: present
    key: "{{jenkins.gpg_key}}"
  become: true

- name: Install Jenkins
  yum:
    name: jenkins
    state: present
  become: true

- name: Change Jenkins JAVA options
  lineinfile:
    dest=/etc/sysconfig/jenkins
    regexp='^JENKINS_JAVA_OPTIONS='
    line=JENKINS_JAVA_OPTIONS= "{{ jenkins.JAVA_OPTIONS }}"
  become: true

- name: Start Jenkins service and enable on boot
  service:
    name: jenkins
    state: started
    enabled: yes
  become: true

- name: read file content
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: filename
  become: true

- name: view the file content
  debug:
    msg: "{{filename.stdout}}"
